about:
  summary: 'GA4GH problematic region files: https://drive.google.com/folderview?id=0B7Ao1qqJJDHQUjVIN3liUUZNWjg&usp=sharing#list'
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 3
extra:
  authors: bcbio
  genome-build: GRCh37
  species: Homo_sapiens
  keywords:
  - GA4GH
  extra-files:
  - README.md
package:
  name: grch37-ga4gh-problem-regions
  version: '20151116'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib

