about:
  summary: " Truth sets from the DREAM genomic challenge 4\n\n https://www.synapse.org/#!Synapse:syn312572/wiki/62018\n\
    \n\n\n Originally retrieved from https://www.synapse.org/#!Synapse:syn2177211\n\
    \n and prepared with this script:\n\n https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/utils/format_dream_truthset.py\n"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 1
extra:
  authors: bcbio
  genome-build: GRCh37
  species: Homo_sapiens
  keywords:
      - validation
package:
  name: grch37-dream-syn4
  version: 2014.08.09
requirements:
  build:
  - gsort
  - htslib
  run:
  - gsort
  - htslib
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
