about:
  summary: "RADAR RNA editing events: (http://www.stanford.edu/~gokulr/database/Human_AG_all_hg19_v2.txt)\n\
    \n installs a BED file of the RADAR events, preconverted to hg38\n\n how this\
    \ file was created:\n\n\n\n 1. Download the hg19 RADAR file and converted to BED\
    \ format.\n\n url=http://www.stanford.edu/~gokulr/database/Human_AG_all_hg19_v2.txt\n\
    \n mkdir -p editing\n\n cd editing\n\n wget -qO- $url | awk 'BEGIN{OFS=\"\\t\"\
    } {print $1,$2,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' | sed \"s/position  position/start\
    \  end/\" > RADAR-hg19.bed\n\n cd ../\n\n 2. Convert RADAR BED file to BED3 format.\n\
    \n cut -f1,2,3 RADAR-hg19.bed > RADAR-hg19.tmp.bed\n\n 3. Get the Crossmap hg19\
    \ to hg38 chain file:\n\n wget http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz\n\
    \n 4. Run Crossmap:\n\n Crossmap.py bed hg19ToHg38.over.chain.gz RADAR-hg19.tmp.bed\
    \ > conversions.bed\n\n 5. Merge original RADAR file with the Crossmap output\n\
    \n wget https://raw.githubusercontent.com/roryk/seqscripts/master/radar-convert-annotations.py\n\
    \n python radar-convert-annotations.py RADAR-hg19.bed conversions.bed RADAR-hg38.bed.gz\n\
    \n\n"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
extra:
  authors: bcbio
  genome-build: hg38
  species: Homo_sapiens
  keywords:
  - rna
package:
  name: hg38-radar-hg38
  version: '1'
requirements:
  build: []
  run: []
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
