about:
  summary: "Ensembl GTF file distributed by Ensembl for hg38-noalt\n\n Cleans GTF\
    \ file by converting chromosome names to standard names \n\n Uses https://github.com/dpryan79/ChromosomeMappings\
    \ to remap the chromosome names\n"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
extra:
  authors: bcbio
  genome-build: hg38-noalt
  species: Homo_sapiens
  keywords:
  - naming
package:
  name: hg38-noalt-gtf
  version: '78'
requirements:
  build: []
  run: []
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
