os:
- linux
#- osx
sudo: required
dist: trusty
language: c
install: travis_wait 119 scripts/travis-setup.sh
script: travis_wait 119 scripts/travis-test.sh
env:
  global:
    secure: bD2+0J824sKGpw8PiyHN99MFTsjZWvNsUMVHP6YA/90QZBRzn1r72eGA20i6UFBFP+34Ekyrt6AhqYT2Tf9LX2GDnkR2XibfvEq+qdNDguU7Py4cFtjq+EqtkhAkUlnVTaK3YgTiRlNz19GWdOCF5G58xbewg4FtluwMcgQ4ufko9CS5l9Ie1xwUzT8LPlPIQiXo8ro3PjjBK4PPz81ifUcZb76f1yJMYwpIFvFdG4b50hHaNmhXCt7+OaCKnSWBboqhF4JHswDteNyzUnq2uBTxBc9GTbdkUYXVu94eW/bqH/v7WZ6qyJwXSDpbEvFLv/ObtMw2N+YM/X+4f96IBnGxpjM4aZUNq57Ek8wmn0wtPO6qkIFrcWbTcQShCPLmTvp0uttUZ2ukP9JgH+vbwDtcca2NPukCa80Zhm0FgwNBUuqhp8DTnAEri6ekHvBnr3g+ALcD2yi1jEXqImmsmVx7yGj7pJkjRYHG3v3i+J+CyaPUudj7oEXF9+MK8NLgZ/40sIlWiWdyX9LU3+A4VUigIj8OmQguosUWN64VgQBXpqgGM3gxcgn5G48XHOU9an/dSoE8bxWcH1vCBwdQpbwFHNtyiao4KvrHPYq/4F9EQmkCtCNKfeLphCCPR8hwHQh/vKUSLECY66/k0UMor9ZIHTqv2XthxWSq0POEvMQ=
