about:
  summary: "RADAR RNA editing events: (http://www.stanford.edu/~gokulr/database/Human_AG_all_hg19_v2.txt)\n\
    \n installs a BED file of the RADAR events"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 1
extra:
  authors: bcbio
  genome-build: hg19
  species: Homo_sapiens
  keywords:
  - RNA
package:
  name: hg19-radar
  version: '1'
requirements:
  build: []
  run: []
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
