build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  build: 1
extra:
  authors: bcbio
  genome-build: GRCh37
  species: Homo_sapiens
  keywords:
      - dbsnp
package:
  name: grch37-dbsnp
  version: '138'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
    #
about:
    summary: "dbsnp 138"
