# Circle CI Yaml
## Docs: https://circleci.com/docs/2.0/configuration-reference/

version: 2

variables:
    setup: &setup
        run:
            name: Setup ggd dependencies
            command: .circleci/setup.sh

    run: &run
        run:
            name: Building/Filtering ggd-recipes
            command: .circleci/run-test.sh 
            no_output_timeout: 1200

    macos: &macos
        macos:
            xcode: "9.4.1" ## Using a macOS VM image (https://circleci.com/docs/2.0/executor-types/)

    linux: &linux
        machine: true ## Using a dedicated Linux VM image (https://circleci.com/docs/2.0/executor-types/)



jobs:
    test-linux:
        <<: *linux
        steps:
            - *setup
            - *run
    
#    test-macos:
#        <<: *macos
#        steps:
#            - *setup
#            - run:
#                name: Building/Filtering ggd-recipes
#                command: *run
#                no_output_timeout: 1200


workflows:
    version: 2
    build-n-filter-ggd-recipes:
        jobs:
            - test-linux
           # - test-macos:
            


    
    
