about:
  summary: 'Medically Interpretable Genes, compiled by Personalis: http://www.genomemedicine.com/content/pdf/s13073-015-0197-4.pdf'
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 1
extra:
  authors: bcbio
  genome-build: hg19
  species: Homo_sapiens
  keywords:
  - clinical
package:
  name: hg19-mig
  version: '20150730'
requirements:
  build: []
  run: []
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
