about:
  summary: " 1000 genomes phase 1 SNP calls\n\n\n\n From the Broad v2.8 resource bundle\n\
    \n https://www.broadinstitute.org/gatk/guide/article.php?id=1213\n\n lifted over\
    \ to hg38 coordinates by Alison Meynert\n\n https://github.com/chapmanb/bcbio-nextgen/issues/817\n"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
extra:
  authors: bcbio
  genome-build: hg38-noalt
  species: Homo_sapiens
  keywords:
  - 1000G
package:
  name: hg38-noalt-1000g_snps
  version: 2.8_hg38_20150522
requirements:
  build: []
  run: []
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
