about:
  summary: "Truth sets from the DREAM genomic challenge 3\n\n https://www.synapse.org/#!Synapse:syn312572/wiki/62018\n\
    \n\n\n Originally retrieved from https://www.synapse.org/#!Synapse:syn2177211\n\
    \n and prepared with this script:\n\n https://github.com/chapmanb/bcbio-nextgen/blob/master/scripts/utils/format_dream_truthset.py\n\
    \n\n\n Converted to hg38 coordinates with CrossMap:\n\n https://github.com/hbc/giab_remap_38\n"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
extra:
  authors: bcbio
  genome-build: hg38
  species: Homo_sapiens
  keywords:
  - truthset
  - validation
package:
  name: hg38-dream-syn3-crossmap
  version: 2014.08.04
requirements:
  build: []
  run: []
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
