about:
  summary: 'small RNA seq annotation from different sources'
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 2
extra:
  authors: bcbio
  genome-build: hg19
  species: Homo_sapiens
  keywords:
  - RNA
  extra-files:
  - mirna_mature.txt.gz
  - miR_Family_Info.txt
  - Summary_Counts.all_predictions.txt
  - miRNA.str
package:
  name: hg19-srnaseq
  version: '20160224'
requirements:
  build:
  - zlib
  - htslib
  - samtools
  run: 
  - zlib
  - htslib
  - samtools
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
